Algoritmo "TESTE"

Var

   nota1, nota2, notafinal : real


Inicio

   escreva("Digite a primeira nota: ")
   leia(nota1)
   
   escreva("Digite a segunda nota: ")
   leia(nota2)
   
   notafinal <- nota1 + nota2
   
   escreval ("NOTA FINAL = ", notafinal:1:1)
   
   se notafinal < 60 entao
      escreva("REPROVADO")
   senao
      escreva("APROVADO")
   fimse






Fimalgoritmo